#!/bin/bash
# Utility functions for use in the cartridge scripts.

function _run_template()
{
	for conf in $@; do
		[ -e "$conf" ] || continue
		/usr/bin/oo-erb "$conf" > "${conf%.erb}"
	done
}

function build_config()
{
    # If config file is not found, use factory default
    local CONFIG_NAME=$1
    CONF_DIR=${OPENSHIFT_REPO_DIR}config/$CONFIG_NAME
    if [ ! -d $CONF_DIR ]; then
        mkdir -p $CONF_DIR
        # Copy factory default
        cp -r ${OPENSHIFT_PHP_DIR}usr/template/config/$CONFIG_NAME/*.erb $CONF_DIR
        _run_template $CONF_DIR/*.erb
        # Remove factory default after generating real configurations
        rm $CONF_DIR/*.erb
    else
        # Generate configs from templates as per normal
        _run_template $CONF_DIR/*.erb
    fi
}

function build_nginx_config()
{
	echo "Building nginx configuration"
    build_config "nginx.d"
}

function build_phpfpm_config()
{
	echo "Building hhvm configuration"
    build_config "hhvm.d"
}
